"use client"

import './globals.css'
import Header from '@/shared/components/Header'; 
import Sidebar from '@/shared/components/Sidebar'; 
import { CssBaseline } from "@mui/material";

// TODO: Investigate 'metadata' and how i can use it in some other place (in non client-side component)
// export const metadata = {
  // title: 'Create Next App',
  // description: 'Generated by create next app',
// }

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <CssBaseline />
        <Header />
        { /* INFO: Temporary hidden */}
        { /* <Sidebar /> */}
        <div>
          {children}
        </div>
      </body>
    </html>
  )
}
